### ISSUE TITLE
Add Issue + PR Templates

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Instatags#1]
> ## Description
> Create a custom Issue and Pull Request Template.
> 
> ## Additional Details
> * Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.
> * Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.
> 
> You can take inspiration from [here](https://github.com/stevemao/github-issue-templates) and check [this](https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f) out to know how to achieve the same.

**Comment by ujju20** [comment]
Can I take up this issue?

**Comment by Ayush7614** [comment]
@ujju20 under which program

**Comment by ujju20** [comment]
I am not a part of DCP'21 how can I participate in it?

**Comment by Ayush7614** [comment]
> I am not a part of DCP'21 how can I participate in it?

@ujju20 registration was closed now

**Comment by DarshGupta1910** [comment]
Hi, I'm DCP's 2021 participant can I solve this issue? 

Thanks

**Comment by Ayush7614** [comment]
> Hi, I'm DCP's 2021 participant can I solve this issue?
> 
> Thanks

Go Ahead @DarshGupta1910

**Comment by Ayush7614** [comment]
@DarshGupta1910 any updates?

**Comment by DarshGupta1910** [comment]
My exams got over today.....Yeah I will do it by today night
