### ISSUE TITLE
Added a Beautiful Poster for project using canva or any other software 

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Instatags#4]
Added a Beautiful Poster for project using canva or any other software

**Comment by bhagyashree-06** [comment]
hey! I am interested
Can you please elaborate the details of poster ?

**Comment by Ayush7614** [comment]
You can make the poster like with various  # of instagrams which you have uses in posting nay post or this thing

**Comment by ushmita4** [comment]
> You can make the poster like with various # of instagrams which you have uses in posting nay post or this thing

I am a graphic designer as well. May I contribute?
